contact_us/urls.py
from django.urls import path

from . import views

app_name = "contact_us"

urlpatterns = [
    path('about', views.about, name='about'),
    path('', views.contact_us, name='contact_us'),
]

fbrowser100M/urls.py
from django.contrib import admin, auth
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
admin.site.site_header = settings.ADMIN_SITE_HEADER

from filebrowser.sites import site
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'projects', views.ProjectView, 'project')

urlpatterns = [
    path('', views.index, name='index'),
    path('', include('pbrowser.urls')),
    path('', include('contact_us.urls')),
    path('admin/filebrowser/', site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('accounts/login/', auth_views.LoginView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path(r'__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

pbrowser/urls.py
from .views import redirect_view
from django.urls import path, re_path
from django.urls import path, include
from . import views


app_name = "pbrowser"

urlpatterns = [
    path('projects/<int:pk>', views.projects, name='projects'),
    path('upload_file', views.upload_file, name='upload_file'),
    path('open_file/<int:pk>', views.open_file, name='open_file'),
    path('copy_project', views.copy_project, name='copy_project'),
    path('files/<int:pk>/<slug:slug1>/<slug:slug2>', views.files, name='files'),
    path('category/<int:pk_cat>/<int:pk_proj>', views.category, name='category'),
]

fbrowser100M/forms.py
import os
from django import forms
from file_manager import check_name
from pbrowser.models import Category, Files100M, Project


class UploadFileForm(forms.ModelForm):
    ALLOWED_TYPES = ['pdf', 'dwg']

    class Meta:
        model = Files100M
        fields = ['project', 'category', 'file']

    def verify_name(self):
        file = self.cleaned_data.get('file', None)
        extension = os.path.splitext(file.name)[1][1:].lower()
        if extension in self.ALLOWED_TYPES:
            return check_name(file,
                              self.cleaned_data['project'],
                              self.cleaned_data['category'])
        else:
            return "Only PDF or DWG supported!"


class ProjectCopyForm(forms.Form):
    project = forms.ModelChoiceField(queryset=Project.objects.all())
    kuerzel = forms.CharField(max_length=3)
    number =  forms.CharField(max_length=3)
    name =  forms.CharField(max_length=30)    

fbrowser100M/views.py
import file_manager
from django.http import HttpResponse
from fbrowser100M.forms import UploadFileForm
from pbrowser.views import filter_projects
from pbrowser.models import Files100M, Project
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect, reverse

from pbrowser.views import upload_file
from .serializers import ProjectSerializer
from rest_framework import viewsets


@login_required(login_url='/admin/login/')
def index(request):
    if request.method == 'POST':
        return upload_file(request)
    projects = filter_projects(request.user)
    folders = list()
    files = list()
    if len(projects) > 0:
        for project in projects:
            folders, files = file_manager.scan_dir(request.user, project.name)
    else:
        projects = list()
        folders = list()

    return render(request, 'index.html', {"projects": projects,
                                          "folders": folders,
                                          "files": files,
                                          'file_upload_form': None})


class ProjectView(viewsets.ModelViewSet):
    serializer_class = ProjectSerializer
    queryset = Project.objects.all()

fbrowser100M/templates/basic/base.html
<!DOCTYPE HTML>
<!--
	ZeroFour by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
{% load django_bootstrap5 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load static %}

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
  <link class="cssdeck" rel="stylesheet"
    href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/css/bootstrap.min.css">
  <link rel="stylesheet"
    href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/css/bootstrap-responsive.min.css" class="cssdeck">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <link rel=”stylesheet” href=”custom.css”>
  <title>Web App 100 Moschee Projekt</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"> <a href="" class="image featured">
          <img src="{% static '/images/amj_logo.png' %}" alt="100 Moschee Logo" class="padding" /></a>
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="navbar-brand disabled" tabindex="-1" aria-disabled="true" href="#">{{ get_version }}</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:logout' %}">Logged in {{request.user}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Administration</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact_us:about' %}">About</a>
          </li>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </ul>
    </div>
  </nav>
</body>

<body>
  {% for message in messages %}
  <div class="container-fluid p-0">
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="True">&times;</span>
      </button>
      {{ message }}
    </div>
  </div>
  {% endfor %}

  <div class="container-fluid">    
    <div> {% block content %}{% endblock %}</div>
  </div>

  <!-- </main> -->

  <hr>
  <!-- Footer Wrapper -->
  <div id="footer-wrapper">
    <footer id="footer" class="container-fluid p-3 my-3 bg-light text-black">
      <div class="row">

        <div class="col-12">
          <div id="copyright">
            <p>&copy; Untitled. All rights reserved</p>
            <p>Design: <a href="http://html5up.net">HTML5 UP</a></p>
          </div>
        </div>
      </div>
    </footer>
  </div>

  <!-- Scripts -->
  <script src="{% static 'assets/js/jquery.dropotron.min.js' %}"></script>
  <script src="{% static 'assets/js/browser.min.js' %}"></script>
  <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
  <script src="{% static 'assets/js/util.js' %}"></script>

</body>

</html>

fbrowser100M/templates/basic/files_view.html
<div class="col-sm-9 col-md-9 col-sm-9 col-lg-10">

    <!-- <h4>{{project.name}}/{{folder}}/{{subfolder}}</h4> -->
    <table class="table">
        <thead>
            <tr>
                {% for field in file_fields %}
                {% if field.name == "file" %}
                    <th>Type</th>
                {% elif field.name != "user"  %}
                    <th>{{field.name|capfirst}}</th>
                {% endif %}
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% if files %}
            {% for file in files %}
            <tr>
                <td>
                    <a href={% url 'pbrowser:open_file' file.id %}>
                        {{file.id}}
                    </a>
                </td>
                <td>
                        {{file.description}}
                    <p>{{file.filename}}</p>
                </td>
                <td>
                    <a target="_blank" href={% url 'pbrowser:open_file' pk=file.id %}>
                        {{file.dateityp}}
                    </a>
                </td>
                <td>
                    {{file.project}}
                </td>
                <td>
                    {{file.category}}
                </td>
                <td>
                    {{file.date}}
                </td>
                <td>
                    {{file.upload_by}}
                </td>
                <!-- <td>
                    {{file.users_str}}
                </td> -->
            </tr>
            {%endfor%}
            {%endif%}

        </tbody>
    </table>

</div>

fbrowser100M/templates/basic/folders_view.html
<div class="col-sm-3 col-md-3 col-sm-3 col-lg-2" style="overflow-y: scroll; overflow-x: hidden; height: 500px;">
    <ul class="nav nav-list">
        {% for proj in projects %}
        <li><label class="tree-toggler nav-header">
                <a href={% url 'pbrowser:projects' pk=proj.id %}>{{proj.name}}</label></a>
            {% if project.name == proj.name %}
            <ul class="nav nav-list tree">
                <li><label class="tree-toggler">Bauvorhaben</label></li>
                <ul class="nav nav-list tree">
                {% for cat in categories %}
                {% if cat.level == 1 %}
                    <li><label class="tree-toggler">
                            <a href={% url 'pbrowser:category' pk_cat=cat.id pk_proj=proj.id %}>{{cat.name}}</label>
                    </li>
                    {% elif cat.level == 2 %}
                    <ul class="nav nav-list tree">
                        <li><label class="tree-toggler">
                                <a href={% url 'pbrowser:category' pk_cat=cat.id pk_proj=proj.id %}>{{cat.name}}</label>

                        </li>
                    </ul>
                    {% elif cat.level == 3 %}
                    <ul class="nav nav-list tree">
                        <li><a href={% url 'pbrowser:category' pk_cat=cat.id pk_proj=proj.id %}>{{cat.name}}</a>
                        </li>
                    </ul>
                    {%endif%}
                    {% endfor %}
                </ul>
            </ul>
        </li>
    </ul>
    {% endif %}

    <li class="divider"></li>
    {%endfor%}

</div>
<script class="cssdeck" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script class="cssdeck" src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>